MOUSEKEY_ENABLE     = no      # Mouse keys
RGBLIGHT_ENABLE     = no     # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
OLED_ENABLE         = yes
OLED_DRIVER         = SSD1306
LTO_ENABLE          = yes
QMK_SETTINGS        = no
TAP_DANCE_ENABLE    		= yes
KEY_OVERRIDE_ENABLE 		= no
EXTRAKEY_ENABLE 			= no
COMBO_ENABLE 				= yes
